[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[build]
  publish = "."
  command = ""
